Снятие покрытия кода тестами
1C-Company/dt-example-plugins pull request #32
Opened 2020-12-06 13:11 UTC by marmyshev

- снятие покрытия
- загрузка покрытия в артефакты

2020-12-06 13:13 UTC, marmyshev commented
Можно посмотреть доступные артефакты jacoco https://github.com/marmyshev/dt-example-plugins/actions/runs/403973707

2020-12-07 11:49 UTC, masofcon requested changes
можно ли сделать отображение процента покрытия через статусный бэйдж на странице README.md?

2020-12-07 11:49 UTC, masofcon commented on bom/pom.xml
> +		<plugin>
форматирование нарушено, не так как во всем файле

2020-12-07 11:49 UTC, masofcon commented on bom/pom.xml
> +					<exclude>**/MdClassPackageImpl*</exclude>
это исключение действительно нужно?

2020-12-07 11:49 UTC, masofcon commented on tests/pom.xml
> +	  <plugin>
форматирование нарушено, не так как во всем файле

2020-12-29 12:11 UTC, marmyshev commented on bom/pom.xml
> +					<exclude>**/MdClassPackageImpl*</exclude>
Да, JaCoCo кидает исключение на этом классе

2020-12-29 16:58 UTC, marmyshev commented
> можно ли сделать отображение процента покрытия через статусный бэйдж на странице README.md?

Быстрого и легкого способа нет:
1. по умолчанию `mvn jacoco:report` формирует отчет только по текущему проекту (бандл-фрагменту) и код из основных бандлов проекта не попадают во отчет. При этом в исходных данных от JaCoCo есть все вызовы. Кажется, что отчет только по тестам - не то что нужно.
2. Используют сервисы типа https://about.codecov.io/ для генерации бэйджей, у гитхаба нативных бэйджей я не нашел
3. Используют бейджи от SonarQube - можно посмотреть пример тут https://github.com/marmyshev/dt-example-plugins для SonarCloud.io (сделано в отдельном реквесте - добавил бейджи уже)

2020-12-30 11:18 UTC, merged